nodeLinker: node-modules
nmHoistingLimits: workspaces
npmRegistryServer: "https://registry.npmjs.org"
npmPublishRegistry: "https://registry.npmjs.org"
npmPublishAccess: public
npmAuthToken: "${NPM_TOKEN-}"
